# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "bd8e1d82962614758ab586220740cc9042f9efa1"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.11.0"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
version = "1.11.0"

[[deps.SpheroidalWaveFunctions]]
deps = ["Artifacts", "Libdl"]
path = "."
uuid = "5995e872-983e-498e-9750-1cefbd4fb98d"
version = "1.0.0-DEV"
